import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/providers/Provider";
import Betamode from "@/components/Betamode";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Block Quill",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-200`}>
        <Betamode />
        <Provider>{children}</Provider>
        <Toaster richColors />
      </body>
    </html>
  );
}
