import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/providers/Provider";
import Betamode from "@/components/Betamode";
import { Toaster } from "sonner";
import GlobalStateProvider from "@/providers/GlobalStateProvider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Block Quill",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen pb-5 relative bg-slate-200`}>
        <Provider>
          <GlobalStateProvider>
            {children}
            <Footer />
          </GlobalStateProvider>
        </Provider>
        <Toaster richColors />
      </body>
    </html>
  );
}
